# Generated by Django 4.2.7 on 2023-11-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_caregiving_type', models.CharField(max_length=50)),
                ('other_requirements', models.TextField()),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('given_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_description', models.TextField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('photo', models.BinaryField()),
                ('gender', models.CharField(max_length=10)),
                ('caregiving_type', models.CharField(max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('house_rules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.member')),
                ('house_number', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caregiver')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=20)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caregiver')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
        ),
    ]
