# Generated by Django 4.2.7 on 2023-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='photo',
            field=models.BinaryField(null=True),
        ),
    ]
